server:
  port: 8083
  
  
spring:
  datasource:
           url: jdbc:mysql://localhost:3306/hotal_service
           username: root
           password: root
           
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: RATING_SERVICE       
eureka:
  instance:
    secure-health-check-url: true
  client:
    fetch-registry: true 
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka   
  
           
           
           
           
           
           
           
           

 